# Generated by Django 4.2.7 on 2026-04-18 10:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('price_per_sqft', models.FloatField(help_text='Price per square foot in USD')),
                ('rental_yield', models.FloatField(help_text='Annual rental yield as percentage (e.g. 5.2 for 5.2%)')),
                ('infra_score', models.FloatField(help_text='Infrastructure score from 0 to 10')),
                ('listing_density', models.FloatField(help_text='Number of active listings in area')),
                ('growth_score', models.FloatField(default=0.0, help_text='Computed growth score (0-10)')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Location Data',
                'verbose_name_plural': 'Location Data',
                'ordering': ['-growth_score'],
            },
        ),
    ]
